###
GET http://localhost:8080/pets/249040b9-283c-4656-b966-d008f5ab84aa
Authorization: Bearer {{auth_token}}

###
PUT http://localhost:8080/pets
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "animal_type": "Cat",
  "name": "Person A",
  "country": "Country A"
}

###
GET http://localhost:8080/pets?limit=1&animal_type=Cat
Authorization: Bearer {{auth_token}}

###
GET http://localhost:8080/pets?after_datetime=2023-11-21T22:47:03.261042Z
Authorization: Bearer {{auth_token}}

###
GET http://localhost:8080/pets
Authorization: Bearer {{auth_token}}

###
DELETE http://localhost:8080/pets/642f33f8-0bca-439b-838f-57396e2e408a
Authorization: Bearer {{auth_token}}

###
PATCH http://localhost:8080/pets/642f33f8-0bca-439b-838f-57396e2e408a
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "country": "USA"
}
